DELIMITER //
CREATE EVENT IF NOT EXISTS optimize_tables ON SCHEDULE EVERY 1 WEEK STARTS '2024-05-29 20:00:00' DO BEGIN DECLARE done INT DEFAULT FALSE;

DECLARE table_name VARCHAR(100);

DECLARE cur CURSOR FOR
SELECT
	TABLE_NAME
FROM
	information_schema.TABLES
WHERE
	TABLE_SCHEMA = DATABASE()
	AND TABLE_TYPE = 'BASE TABLE';

DECLARE CONTINUE HANDLER FOR NOT FOUND
SET
	done = TRUE;

OPEN cur;

read_loop: LOOP FETCH cur INTO table_name;

IF done THEN LEAVE read_loop;

END IF;

SET
	@sql = CONCAT('OPTIMIZE TABLE ', table_name);

PREPARE stmt
FROM
	@sql;

EXECUTE stmt;

DEALLOCATE PREPARE stmt;

END LOOP;

CLOSE cur;

END//
DELIMITER ;